spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/breaking_news?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: lunan998998

mybatis:
  configuration:
    map-underscore-to-camel-case: true  # 驼峰命名法和下划线命名自动转化